name: Sync to CodeCommit

on:
  push:
    branches:
      - main # 監視するブランチを指定

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4 # バージョンをv4に更新
        with:
          role-to-assume: arn:aws:iam::398649269234:role/ogata-codecommit-oidc
          aws-region: ap-northeast-1

      - name: Verify AWS credentials
        run: aws sts get-caller-identity # 追加: IAMロールの確認

      - name: Configure git to use AWS CodeCommit credentials
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true

      - name: Add CodeCommit remote
        run: |
          git remote add codecommit https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/ogata-codecommit-try-study

      - name: Set up git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Check git remote
        run: git remote -v

      - name: Check git log
        run: git log -1

      - name: Initial push to CodeCommit
        run: |
          # リモートリポジトリが空であることを前提にして、初回のプッシュを行う
          git push codecommit main --force || git push codecommit main --set-upstream