name: Sync to CodeCommit

on:
  push:
    branches:
      - main # 監視するブランチを指定

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      #      - name: Checkout repository
      #        uses: actions/checkout@v2
      #      - name: Configure AWS credentials using OIDC
      - uses: aws-actions/configure-aws-credentials@v3 # バージョンをv3に更新
        with:
          role-to-assume: arn:aws:iam::398649269234:role/ogata-codecommit-oidc
          aws-region: ap-northeast-1

      - name: Sync to CodeCommit
        run: |
          git remote add codecommit https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/ogata-try-codepipeline-study
          git push codecommit main